sudo: false
language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc

script: ./gradlew build

after_script:
- for f in "websockets-example/build/outputs/lint-results*.html"; do pandoc $f -t plain; done
- for f in "websockets-rxjava-example/build/outputs/lint-results*.html"; do pandoc $f -t plain; done
